name = "New Haven (Beta — JEI tree names)"
author = "SirZalea"
version = "0.4.0-midsummer.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "195ee6c5f7cad9dec527250dc963ab6a5faad8544dd5ea244433765e3744f398"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.235"
