name = "New Haven"
author = "SirZalea"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "49fa0204fb9e856b0bc686edfca8ee4dacda206a92b0f2e2b704bb3243b57514"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.235"
