name = "New Haven"
author = "SirZalea"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1fcec395fdaf4751e478b32e8c9715b5ef1d9d20b5c1a82f9559eaf9108616de"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.235"
