name = "New Haven"
author = "SirZalea"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "acb263f39f8332f8d320497874d9a57336ed6fef20ebbe4eda12bf1784d51972"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.235"
