name = "New Haven (Beta — JEI tree names)"
author = "SirZalea"
version = "0.4.0-midsummer.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "77c4fd2b65405b0f6e87af205f8d0c3127a559848c92307bed6f480eb925340a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.235"
