name = "New Haven (Beta — JEI tree names)"
author = "SirZalea"
version = "0.4.0-midsummer.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aa3e09a8b12fbfba9a65c1f44fbafcea5a5a8e24c31d606f7a8432e8b16f4341"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.235"
