name = "New Haven (Beta — JEI tree names)"
author = "SirZalea"
version = "0.4.0-midsummer.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3302801187c7dcb4fcb5afa525280c1453ecbe9b5c2f9cfd2400d71035b7a00d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.235"
