name = "New Haven (Beta — JEI tree names)"
author = "SirZalea"
version = "0.4.0-midsummer.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b2e8cc9e06911f5b152b812ce4a25ee028368200ef6cf673b978ad0a403290a3"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.235"
