name = "New Haven (Beta — JEI tree names)"
author = "SirZalea"
version = "0.4.0-midsummer.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "60984f8005934905603a965c97453a78d591aad9091db373a577b002b8ee52ac"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.235"
