name = "New Haven (Beta — JEI tree names)"
author = "SirZalea"
version = "0.4.0-midsummer.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0282984bae561d6b7ab8240e68cadbb2778db5db2e9029e992aead34550bda71"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.235"
