name = "New Haven (Beta — JEI tree names)"
author = "SirZalea"
version = "0.4.0-midsummer.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0dd7922badfd62772d7b36160a682f8b2b0981053744f9ee9c18ab4d8c6b68b3"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.235"
