name = "New Haven (Beta — JEI tree names)"
author = "SirZalea"
version = "0.4.0-midsummer.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "94b6674afbb85f1633afaebbad2c9ea95469cb3d5b66ae8e30645eda5335770a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.235"
