name = "New Haven (Beta — JEI tree names)"
author = "SirZalea"
version = "0.4.0-midsummer.12"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3c25b20bba0c0f4e60317db740b8e93b6d54e96e7f3a76da5a3d6a271aba9411"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.235"
