name = "New Haven (Beta — JEI tree names)"
author = "SirZalea"
version = "0.4.0-midsummer.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "00fae88e91ff6235932c9c7b5b0a1002a6083cd0e68ab826bcd52ff761148884"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.235"
