name = "New Haven"
author = "SirZalea"
version = "0.4.0-midsummer.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "25ccb00186a02223b38ec98313268205c06dbc1a2881c0f86a3113ad273758e1"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.235"
