name = "New Haven (Beta — JEI tree names)"
author = "SirZalea"
version = "0.4.0-midsummer.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c8b89e34864b8e020bf2ca276d4ac8560fed19182a2d065cf50962d4f988d1c7"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.235"
