name = "New Haven (Beta — JEI tree names)"
author = "SirZalea"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f3c43a42039c110a1951c2a196936e6c7058ea4e4da78f0d687f9e2c57b3f729"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.235"
