name = "New Haven (Beta — JEI tree names)"
author = "SirZalea"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9f53eeb4cbaefeb06c26279d60bde3e0c4100237d330c0f30e5a1a70d6627c03"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.235"
