name = "New Haven"
author = "SirZalea"
version = "0.4.0-midsummer.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1523269e2674e31c5ec836e70c11bee13dc62a26047a7c8a5960b8caec6a1c87"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.235"
