name = "New Haven (Beta — JEI tree names)"
author = "SirZalea"
version = "0.4.0-midsummer.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "44d8a2fe3699a791ae1135e3ff4146b24d7e1523a3e3ef4ea55c67c35f66e6c1"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.235"
