name = "New Haven (Beta — JEI tree names)"
author = "SirZalea"
version = "0.4.0-midsummer.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "39f1a13879992cf5a44856c1d1539e5b238bf7edb61d309dcdd94eb171513379"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.235"
