name = "New Haven (Beta — JEI tree names)"
author = "SirZalea"
version = "0.4.0-midsummer.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1fc778a8cf9e23ba20734bba6a61cac779b7c3e6e99c4772b94bf532e37381e5"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.235"
