name = "New Haven"
author = "SirZalea"
version = "0.4.0-midsummer.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ef93eb15c6699c8924657aaee64fe76b86923bd762cd9e8def9be91604dbce59"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.235"
